# general
data_dir: data
cuda: 0
seed: 0
exps_path: exps

# frame processing
flip_p: 0.5

# encoder
use_clip: openai/clip-vit-large-patch14
num_epochs: 2
lr: 0.001
classifier_lr: 0.001
batch_size: 2
gradient_accumulation_steps: 2
output_size: 1024

# prompt learning
prompt_learning: True
num_context_vision: 8
prompt_depth_vision: 12
dim_context_vision: 1024
num_context_text: 6
prompt_depth_text: 12
dim_context_text: 768